version: '3'
services:
  db:
    image: "postgres:9.3-alpine"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=savethat
      - POSTGRES_PASSWORD=P@ssword123
      - POSTGRES_DB=savethat_development
    ports:
      - "5432:5432"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/savethat
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres: